package za.ac.ufh.safety.incidents;

import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.test.util.ReflectionTestUtils;
import za.ac.ufh.safety.common.ApiException;
import za.ac.ufh.safety.user.User;
import za.ac.ufh.safety.responders.ResponderRepository;
import za.ac.ufh.safety.user.UserRepository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class IncidentServiceTest {

    private IncidentRepository incidents;
    private UserRepository users;
    private ResponderRepository responders;
    private IncidentService service;

    @BeforeEach
    void setUp() {
        incidents = mock(IncidentRepository.class);
        users = mock(UserRepository.class);
        responders = mock(ResponderRepository.class);
        service = new IncidentService(incidents, users, responders, new PriorityCalculator());
        when(incidents.save(any(Incident.class))).thenAnswer(call -> call.getArgument(0));
    }

    // userId is generated by the database and so has no setter on the entity.
    // In a unit test there is no database, so we set the field directly.
    private User user(long userId, String role) {
        User user = new User();
        ReflectionTestUtils.setField(user, "userId", userId);
        user.setEmail(userId + "@ufh.ac.za");
        user.setRole(role);
        when(users.findByEmailIgnoreCase(user.getEmail())).thenReturn(Optional.of(user));
        return user;
    }

    private CreateIncidentRequest report(IncidentType type, String description,
                                         Double latitude, Double longitude) {
        return new CreateIncidentRequest(type, description, latitude, longitude, 12.0, false);
    }

    @Test
    void studentCanReportAndTheServerSetsStatusAndPriority() {
        User student = user(7, "student");

        IncidentCreatedResponse response = service.create(student.getEmail(),
            report(IncidentType.MEDICAL, "Someone collapsed.", -32.78331, 26.84971));

        assertThat(response.status()).isEqualTo(IncidentStatus.REPORTED);
        assertThat(response.priority()).isEqualTo(2);
        assertThat(response.locationSource()).isEqualTo("device");

        ArgumentCaptor<Incident> saved = ArgumentCaptor.forClass(Incident.class);
        verify(incidents).save(saved.capture());
        assertThat(saved.getValue().getReporterUserId()).isEqualTo(7L);
    }

    // A report with no coordinates is still a report. Refusing it would mean
    // the system fails exactly when a student has no GPS fix.
    @Test
    void aReportWithoutCoordinatesIsAccepted() {
        User student = user(7, "student");

        IncidentCreatedResponse response = service.create(student.getEmail(),
            report(IncidentType.UNSAFE, null, null, null));

        assertThat(response.locationSource()).isEqualTo("none");
    }

    @Test
    void halfACoordinatePairIsRejected() {
        User student = user(7, "student");

        assertThatThrownBy(() -> service.create(student.getEmail(),
                report(IncidentType.THEFT, null, -32.78331, null)))
            .isInstanceOf(ApiException.class)
            .hasMessageContaining("both latitude and longitude");
    }

    @Test
    void otherRequiresADescription() {
        User student = user(7, "student");

        assertThatThrownBy(() -> service.create(student.getEmail(),
                report(IncidentType.OTHER, "   ", null, null)))
            .isInstanceOf(ApiException.class)
            .satisfies(thrown -> assertThat(((ApiException) thrown).getField()).isEqualTo("description"));
    }

    @Test
    void campusControlCannotFileAReport() {
        User officer = user(3, "campus_control");

        assertThatThrownBy(() -> service.create(officer.getEmail(),
                report(IncidentType.FIRE, null, null, null)))
            .isInstanceOf(ApiException.class)
            .satisfies(thrown -> assertThat(((ApiException) thrown).getStatus()).isEqualTo(403));
    }

    // The access rule that matters: a student must never be handed another
    // person's incidents, so the query is scoped by reporter rather than
    // filtered after the fact.
    @Test
    void aStudentOnlySeesTheirOwnIncidents() {
        User student = user(7, "student");
        when(incidents.findByReporterUserId(eq(7L), any(Pageable.class)))
            .thenReturn(emptyPage());

        service.list(student.getEmail(), null, null, null);

        verify(incidents).findByReporterUserId(eq(7L), any(Pageable.class));
    }

    @Test
    void aResponderOnlySeesIncidentsAssignedToThem() {
        User responder = user(5, "responder");
        when(incidents.findByAssignedResponderId(eq(5L), any(Pageable.class)))
            .thenReturn(emptyPage());

        service.list(responder.getEmail(), null, null, null);

        verify(incidents).findByAssignedResponderId(eq(5L), any(Pageable.class));
    }

    @Test
    void campusControlSeesEveryIncident() {
        User officer = user(3, "campus_control");
        when(incidents.findAll(any(Pageable.class))).thenReturn(emptyPage());

        service.list(officer.getEmail(), null, null, null);

        verify(incidents).findAll(any(Pageable.class));
    }

    // The contract pages from 1; Spring Data pages from 0. Getting this wrong
    // silently skips the first page of results.
    @Test
    void pageOneMapsToSpringDataPageZero() {
        User admin = user(3, "admin");
        ArgumentCaptor<Pageable> pageable = ArgumentCaptor.forClass(Pageable.class);
        when(incidents.findAll(any(Pageable.class))).thenReturn(emptyPage());

        IncidentListResponse response = service.list(admin.getEmail(), null, 1, 20);

        verify(incidents).findAll(pageable.capture());
        assertThat(pageable.getValue().getPageNumber()).isZero();
        assertThat(response.page()).isEqualTo(1);
        assertThat(response.pageSize()).isEqualTo(20);
    }

    @Test
    void pageSizeAboveTheMaximumIsRejected() {
        User admin = user(3, "admin");

        assertThatThrownBy(() -> service.list(admin.getEmail(), null, 1, 101))
            .isInstanceOf(ApiException.class)
            .satisfies(thrown -> assertThat(((ApiException) thrown).getField()).isEqualTo("pageSize"));
    }

    @Test
    void anUnknownStatusFilterIsABadRequestNotAServerError() {
        User admin = user(3, "admin");

        assertThatThrownBy(() -> service.list(admin.getEmail(), "en-route", null, null))
            .isInstanceOf(ApiException.class)
            .satisfies(thrown -> assertThat(((ApiException) thrown).getStatus()).isEqualTo(400));
    }

    private Page<Incident> emptyPage() {
        return new PageImpl<>(List.of());
    }
}
