package za.ac.ufh.safety.incidents;

import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.test.util.ReflectionTestUtils;
import za.ac.ufh.safety.common.ApiException;
import za.ac.ufh.safety.user.User;
import za.ac.ufh.safety.user.UserRepository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * GET /api/incidents/{id}, PATCH .../status and POST .../cancel.
 *
 * The access rules matter more than the happy paths here, so most of these
 * tests are about who is refused rather than who succeeds.
 */
class IncidentLifecycleTest {

    private IncidentRepository incidents;
    private UserRepository users;
    private IncidentService service;

    @BeforeEach
    void setUp() {
        incidents = mock(IncidentRepository.class);
        users = mock(UserRepository.class);
        service = new IncidentService(incidents, users, new PriorityCalculator());
        when(incidents.save(any(Incident.class))).thenAnswer(call -> call.getArgument(0));
    }

    // userId is generated by the database so the entity has no setter for it.
    private User user(long userId, String role) {
        User user = new User();
        ReflectionTestUtils.setField(user, "userId", userId);
        user.setEmail(userId + "@ufh.ac.za");
        user.setFullName("User " + userId);
        user.setRole(role);
        when(users.findByEmailIgnoreCase(user.getEmail())).thenReturn(Optional.of(user));
        when(users.findById(userId)).thenReturn(Optional.of(user));
        return user;
    }

    private Incident incident(long incidentId, long reporterUserId, IncidentStatus status) {
        Incident incident = new Incident();
        ReflectionTestUtils.setField(incident, "incidentId", incidentId);
        incident.setReporterUserId(reporterUserId);
        incident.setType(IncidentType.MEDICAL);
        incident.setStatus(status);
        incident.setPriority(2);
        incident.setAnonymous(false);
        incident.setLatitude(-32.78331);
        incident.setLongitude(26.84971);
        ReflectionTestUtils.setField(incident, "locationSource", "device");
        when(incidents.findById(incidentId)).thenReturn(Optional.of(incident));
        return incident;
    }

    @Test
    void aStudentCanReadTheirOwnIncident() {
        User student = user(7, "student");
        incident(42, 7, IncidentStatus.REPORTED);

        IncidentDetail detail = service.get(student.getEmail(), 42L);

        assertThat(detail.incidentId()).isEqualTo(42L);
        assertThat(detail.reporter().userId()).isEqualTo(7L);
        assertThat(detail.assignedResponder()).isNull();
    }

    // 404 rather than 403 on purpose: a 403 would confirm the incident exists
    // and let somebody count incidents by walking ids.
    @Test
    void aStudentReadingSomebodyElsesIncidentGetsNotFound() {
        User student = user(8, "student");
        incident(42, 7, IncidentStatus.REPORTED);

        assertThatThrownBy(() -> service.get(student.getEmail(), 42L))
            .isInstanceOf(ApiException.class)
            .hasMessageContaining("No such incident");
    }

    @Test
    void anAnonymousIncidentHidesTheReporter() {
        User control = user(2, "campus_control");
        Incident anonymous = incident(42, 7, IncidentStatus.REPORTED);
        anonymous.setAnonymous(true);

        IncidentDetail detail = service.get(control.getEmail(), 42L);

        assertThat(detail.reporter()).isNull();
    }

    @Test
    void campusControlCanMoveAnIncidentForward() {
        User control = user(2, "campus_control");
        incident(42, 7, IncidentStatus.REPORTED);

        IncidentDetail detail = service.updateStatus(control.getEmail(), 42L,
            new UpdateStatusRequest(IncidentStatus.TRIAGED, "Confirmed by phone."));

        assertThat(detail.status()).isEqualTo(IncidentStatus.TRIAGED);
    }

    @Test
    void anIllegalTransitionIsRejected() {
        User control = user(2, "campus_control");
        incident(42, 7, IncidentStatus.RESOLVED);

        assertThatThrownBy(() -> service.updateStatus(control.getEmail(), 42L,
            new UpdateStatusRequest(IncidentStatus.REPORTED, null)))
            .isInstanceOf(ApiException.class)
            .hasMessageContaining("already resolved");
    }

    @Test
    void aResponderCannotTouchAnIncidentAssignedToSomebodyElse() {
        User responder = user(5, "responder");
        Incident other = incident(42, 7, IncidentStatus.ASSIGNED);
        other.setAssignedResponderId(6L);

        assertThatThrownBy(() -> service.updateStatus(responder.getEmail(), 42L,
            new UpdateStatusRequest(IncidentStatus.EN_ROUTE, null)))
            .isInstanceOf(ApiException.class)
            .hasMessageContaining("not assigned to you");
    }

    @Test
    void aResponderCanMoveTheirOwnAssignment() {
        User responder = user(5, "responder");
        Incident mine = incident(42, 7, IncidentStatus.ASSIGNED);
        mine.setAssignedResponderId(5L);

        IncidentDetail detail = service.updateStatus(responder.getEmail(), 42L,
            new UpdateStatusRequest(IncidentStatus.EN_ROUTE, null));

        assertThat(detail.status()).isEqualTo(IncidentStatus.EN_ROUTE);
        assertThat(detail.assignedResponder().responderId()).isEqualTo(5L);
    }

    // Repeated taps on a bad signal should not surface as an error.
    @Test
    void settingTheStatusItAlreadyHasIsANoOp() {
        User control = user(2, "campus_control");
        incident(42, 7, IncidentStatus.TRIAGED);

        IncidentDetail detail = service.updateStatus(control.getEmail(), 42L,
            new UpdateStatusRequest(IncidentStatus.TRIAGED, null));

        assertThat(detail.status()).isEqualTo(IncidentStatus.TRIAGED);
    }

    @Test
    void aStudentCanCancelTheirOwnFalseAlarm() {
        User student = user(7, "student");
        incident(42, 7, IncidentStatus.REPORTED);

        IncidentDetail detail = service.cancel(student.getEmail(), 42L,
            new CancelIncidentRequest("Pressed by accident."));

        assertThat(detail.status()).isEqualTo(IncidentStatus.CANCELLED);
    }

    @Test
    void aStudentCannotCancelSomebodyElsesIncident() {
        User student = user(8, "student");
        incident(42, 7, IncidentStatus.REPORTED);

        assertThatThrownBy(() -> service.cancel(student.getEmail(), 42L,
            new CancelIncidentRequest(null)))
            .isInstanceOf(ApiException.class)
            .hasMessageContaining("only cancel an incident you reported");
    }

    @Test
    void aResolvedIncidentCannotBeCancelled() {
        User student = user(7, "student");
        incident(42, 7, IncidentStatus.RESOLVED);

        assertThatThrownBy(() -> service.cancel(student.getEmail(), 42L,
            new CancelIncidentRequest(null)))
            .isInstanceOf(ApiException.class)
            .hasMessageContaining("already resolved");
    }
}
